title: CertUtil File Download or Split (Sysmon)
id: 7c1d5f2e-1a3b-4d9f-b6e8-2f7a9c5e4b3d
status: experimental
description: Detects certutil.exe usage for downloading files, splitting files, or accessing URLs.
author: Khaireddine
date: 2025/08/18
logsource:
  product: windows
  category: process_creation
  service: sysmon
detection:
  sel_img:
    Image|endswith: 
      - '\certutil.exe'
  sel_cmd:
    CommandLine|contains_any:
      - ' -urlcache '
      - ' -split '
      - ' http://'
      - ' https://'
  condition: sel_img and sel_cmd
fields: [ UtcTime, Image, CommandLine, ParentImage, ParentCommandLine, User ]
falsepositives: [ Admin usage of certutil for legitimate file operations ]
level: high
tags: [ attack.command_and_control, attack.t1105 ]