title: Suspicious File Download Utilities in Temp (Sysmon)
id: 7c1d5f2e-1a3b-4d9f-b6e8-2f7a9c5e4b3d
status: experimental
description: Detects suspicious file download or staging activity using built-in utilities like certutil, bitsadmin, PowerShell, curl, or sqlcmd, often abused for T1105 (Ingress Tool Transfer).
author: Khaireddine
date: 2025/09/08
logsource:
  product: windows
  category: process_creation
  service: sysmon
detection:
  select_id:
    EventID: 1
  certutil:
    Image|endswith: '\certutil.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains|all:
      - '-urlcache'
      - '-split'
      - '-f'
    CommandLine|contains:
      - 'http'
      - 'https'
  bitsadmin:
    Image|endswith: '\bitsadmin.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains|all:
      - '/transfer'
    CommandLine|contains:
      - 'http'
      - 'https'
  powershell_web_A:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains:
      - 'New-Object'
      - 'Out-File'
      - 'Invoke-Item'
      - 'Invoke-Expression'
  powershell_web_B:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains:
      - 'DownloadFile'
      - 'DownloadString'
      - 'WebClient'
  powershell_web_C:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains:
      - 'http'
      - 'https'
  cmd_curl:
    Image|endswith: '\cmd.exe'
    CommandLine|contains|all:
      - 'Curl.exe'
    CommandLine|contains:
      - '-k'
      - '--insecure'
      - '-o'
      - '--output'
  cmd_curl_urls:
    CommandLine|contains:
      - 'http'
      - 'https'
  powershell_iwr:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
  powershell_iwr_1:
    CommandLine|contains:
      - 'iwr'
      - 'Invoke-WebRequest'
  powershell_iwr_2:
    CommandLine|contains:
      - 'http'
      - 'https'
  powershell_sqlcmd_zip:
    Image|endswith: '\powershell.exe'
    CommandLine|contains|all:
      - 'sqlcmd'
      - '-i'
    CommandLine|contains:
      - 'http'
      - 'https'
  cleanup_proc:
    Image|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
  cleanup_del:
    CommandLine|contains|all:
      - ' del '
      - '>nul 2>&1'
  cleanup_removeitem:
    CommandLine|contains|all:
      - 'Remove-Item'
      - '$env:TEMP'
      - '-Force'
      - '-ErrorAction Ignore'
  cleanup_rm:
    CommandLine|contains|all:
      - 'rm'
      - '2>$null'
  condition: >
    select_id and (
      certutil
      or bitsadmin
      or (powershell_web_A and powershell_web_B and powershell_web_C)
      or (cmd_curl and cmd_curl_urls)
      or (powershell_iwr and powershell_iwr_1 and powershell_iwr_2)
      or powershell_sqlcmd_zip
      or (cleanup_proc and (cleanup_del or cleanup_removeitem or cleanup_rm))
    )
fields:
  - UtcTime
  - Image
  - CommandLine
  - ParentImage
  - ParentCommandLine
  - User
falsepositives:
  - Legitimate admin usage of certutil
  - Legitimate automation using bitsadmin or curl
  - Legitimate PowerShell web requests for updates
level: high
tags:
  - attack.command_and_control
  - attack.t1105
