title: Suspicious File Download Utilities in Temp (Sysmon)
id: 7c1d5f2e-1a3b-4d9f-b6e8-2f7a9c5e4b3d
status: experimental
description: Detects suspicious file download or staging activity using built-in utilities like certutil, bitsadmin, PowerShell, curl, or sqlcmd, often abused for T1105 (Ingress Tool Transfer).
author: Khaireddine
date: 2025/09/08
logsource:
  product: windows
  category: process_creation
  service: sysmon
detection:
  certutil:
    Image|endswith: '\certutil.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains|all:
      - '-urlcache'
      - '-split'
      - '-f'
    CommandLine|contains:
      - 'http://'
      - 'https://'
    CurrentDirectory|contains: '\Temp\'

  bitsadmin:
    Image|endswith: '\bitsadmin.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains|all:
      - '/transfer'
      - '/priority'
      - 'high'
    CommandLine|contains:
      - 'http://'
      - 'https://'
    CurrentDirectory|contains: '\Temp\'

  powershell_webclient:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains:
      - 'DownloadFile'
      - 'DownloadString'
      - 'WebClient'
      - 'Out-File'
      - 'Invoke-Item'
      - 'Invoke-Expression'
    CommandLine|contains:
      - 'http://'
      - 'https://'
    CurrentDirectory|contains: '\Temp\'

  cmd_curl:
    Image|endswith: '\cmd.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains|all:
      - 'curl.exe'
      - '-k'
    CommandLine|contains:
      - 'http://'
      - 'https://'
      - '\users\'
      - 'Temp'
      - '\programdata\'
    CurrentDirectory|contains: '\Temp\'

  powershell_iwr:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains:
      - 'iwr'
      - 'Invoke-WebRequest'
    CommandLine|contains:
      - 'http://'
      - 'https://'
    CurrentDirectory|contains: '\Temp\'

  powershell_sqlcmd_zip:
    Image|endswith: '\powershell.exe'
    ParentImage|endswith:
      - '\cmd.exe'
      - '\powershell.exe'
    CommandLine|contains|all:
      - '&'
      - '{sqlcmd'
    CommandLine|contains:
      - 'http://'
      - 'https://'
      - '.zip'
    CurrentDirectory|contains: '\Temp\'

  condition: certutil or bitsadmin or powershell_webclient or cmd_curl or powershell_iwr or powershell_sqlcmd_zip

fields:
  - UtcTime
  - Image
  - CommandLine
  - ParentImage
  - ParentCommandLine
  - User
falsepositives:
  - Legitimate admin usage of certutil, bitsadmin, curl, or PowerShell web requests
level: high
tags:
  - attack.command_and_control
  - attack.t1105
